### ISSUE TITLE
Connection to MTsocketAPI refused for Golang client

### ISSUE THREAD

**Issue by theghostmac** [MTsocketAPI/MT5-API#1]
Hi there,

I am trying to write a client to make use of the MTsocketAPI, but it says:
```shell
Error:  dial tcp 127.0.0.1:77: connect: connection refused
```
I run a telnet command and get:
```shell
❯ telnet localhost 77
Trying ::1...
telnet: connect to address ::1: Connection refused
Trying 127.0.0.1...
telnet: connect to address 127.0.0.1: Connection refused
telnet: Unable to connect to remote host
```

I think the issue has something to do with ws2_32.dll windows library but I just want to be sure. 

Can MTsocketAPI be used on a Mac M1 Pro?

PS: I have set the MTsocketAPI on my Expert Advisors:
![image](https://github.com/MTsocketAPI/MT5-API/assets/83423188/8603a897-89ff-4353-938d-fa1a9c06227f)

**Comment by MTsocketAPI** [comment]
Dear MacBobby,

 

The API must be run on a Windows computer but you can connect to it from a Mac computer with the professional license.

 

Best regards,

 



 <https://www.mtsocketapi.com/> MTsocketAPI

 

De: MacBobby Chibuzor ***@***.***> 
Enviado el: lunes, 18 de diciembre de 2023 3:10
Para: MTsocketAPI/MT5-API ***@***.***>
CC: Subscribed ***@***.***>
Asunto: [MTsocketAPI/MT5-API] Connection to MTsocketAPI refused for Golang client (Issue #1)

 

Hi there,

I am trying to write a client to make use of the MTsocketAPI, but it says:

Error:  dial tcp 127.0.0.1:77: connect: connection refused

I run a telnet command and get:

❯ telnet localhost 77
Trying ::1...
telnet: connect to address ::1: Connection refused
Trying 127.0.0.1...
telnet: connect to address 127.0.0.1: Connection refused
telnet: Unable to connect to remote host

I think the issue has something to do with ws2_32.dll windows library but I just want to be sure.

Can MTsocketAPI be used on a Mac M1 Pro?
